import { tr } from '@/i18n/locales.js'

// Your portfolio pieces. `media.src` empty = styled placeholder.
// Title, summary, deliverables and result live in translations.js under 'project.<id>.*'.
export const categories = ['all', 'recipes', 'beauty', 'books', 'lifestyle'].map((id) => ({
  id,
  label: tr(`category.${id}`),
}))

const text = (id) => ({
  title: tr(`project.${id}.title`),
  summary: tr(`project.${id}.summary`),
  deliverables: tr(`project.${id}.deliverables`),
  result: tr(`project.${id}.result`),
})

export const projects = [
  {
    id: 'oat-pancakes',
    ...text('oat-pancakes'),
    brand: 'Mill & Mortar',
    category: 'recipes',
    media: { type: 'video', src: '', poster: '' },
    tone: 'dusk',
    year: 2026,
    featured: true,
    published: true,
    order: 1,
  },
  {
    id: 'miso-butter-pasta',
    ...text('miso-butter-pasta'),
    brand: 'Nordic Pantry',
    category: 'recipes',
    media: { type: 'video', src: '', poster: '' },
    tone: 'sky',
    year: 2026,
    featured: true,
    published: true,
    order: 2,
  },
  {
    id: 'glow-routine',
    ...text('glow-routine'),
    brand: 'Lumen Skin',
    category: 'beauty',
    media: { type: 'video', src: '', poster: '' },
    tone: 'night',
    year: 2026,
    featured: true,
    published: true,
    order: 3,
  },
  {
    id: 'olive-oil-cake',
    ...text('olive-oil-cake'),
    brand: 'Oliva Brava',
    category: 'recipes',
    media: { type: 'image', src: '', poster: '' },
    tone: 'mist',
    year: 2025,
    featured: false,
    published: true,
    order: 4,
  },
  {
    id: 'reading-nook',
    ...text('reading-nook'),
    brand: 'Paperlight Books',
    category: 'books',
    media: { type: 'video', src: '', poster: '' },
    tone: 'sky',
    year: 2025,
    featured: false,
    published: true,
    order: 5,
  },
  {
    id: 'weeknight-ramen',
    ...text('weeknight-ramen'),
    brand: 'Kettle House',
    category: 'recipes',
    media: { type: 'video', src: '', poster: '' },
    tone: 'night',
    year: 2025,
    featured: false,
    published: true,
    order: 6,
  },
  {
    id: 'lip-oil',
    ...text('lip-oil'),
    brand: 'Dewdrop Beauty',
    category: 'beauty',
    media: { type: 'image', src: '', poster: '' },
    tone: 'dusk',
    year: 2025,
    featured: false,
    published: true,
    order: 7,
  },
  {
    id: 'smoothie-bowl',
    ...text('smoothie-bowl'),
    brand: 'Greenbowl',
    category: 'recipes',
    media: { type: 'video', src: '', poster: '' },
    tone: 'sky',
    year: 2024,
    featured: false,
    published: true,
    order: 8,
  },
  {
    id: 'sunday-reset',
    ...text('sunday-reset'),
    brand: 'Linen & Co',
    category: 'lifestyle',
    media: { type: 'video', src: '', poster: '' },
    tone: 'mist',
    year: 2024,
    featured: false,
    published: true,
    order: 9,
  },
]
